from django.db import models


class NotificationType(models.TextChoices):
    MAINTENANCE_APPROACHING = "MAINTENANCE_APPROACHING"
    MAINTENANCE_DUE = "MAINTENANCE_DUE"
    MAINTENANCE_OVERDUE = "MAINTENANCE_OVERDUE"
    CRITICAL_COMPONENT = "CRITICAL_COMPONENT"
    LOW_STOCK = "LOW_STOCK"
    WORK_ORDER_ASSIGNED = "WORK_ORDER_ASSIGNED"
    WORK_ORDER_COMPLETED = "WORK_ORDER_COMPLETED"
