# Generated by Django 5.2.17 on 2026-08-17 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mission_type",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PlatformType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "platform_type",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="UAVClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "mtow_min_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "mtow_max_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_demo", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uav_class",
                "ordering": ("sort_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="UAV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("registration_number", models.CharField(max_length=64)),
                ("serial_number", models.CharField(max_length=128)),
                ("manufacturer", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=128)),
                (
                    "maintenance_approach",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("CLASS_SPECIFIC", "Class Specific"),
                        ],
                        default="CLASS_SPECIFIC",
                        max_length=32,
                    ),
                ),
                (
                    "mtow_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("production_date", models.DateField(blank=True, null=True)),
                ("inventory_entry_date", models.DateField(blank=True, null=True)),
                (
                    "total_flight_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_flight_count", models.PositiveIntegerField(default=0)),
                ("total_flight_cycles", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("MAINTENANCE", "Maintenance"),
                            ("GROUNDED", "Grounded"),
                            ("RETIRED", "Retired"),
                        ],
                        default="READY",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uavs",
                        to="maintenance.maintenancetemplate",
                    ),
                ),
                (
                    "mission_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uavs",
                        to="uavs.missiontype",
                    ),
                ),
                (
                    "platform_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uavs",
                        to="uavs.platformtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uav_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uavs",
                        to="uavs.uavclass",
                    ),
                ),
            ],
            options={
                "db_table": "uav",
            },
        ),
        migrations.AddConstraint(
            model_name="missiontype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_mission_code_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_platform_code_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="uavclass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_uav_class_code_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="uav",
            index=models.Index(fields=["status"], name="uav_status_ffe87a_idx"),
        ),
        migrations.AddIndex(
            model_name="uav",
            index=models.Index(
                fields=["uav_class", "platform_type", "mission_type"],
                name="uav_uav_cla_02bd59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uav",
            index=models.Index(
                fields=["maintenance_template"], name="uav_mainten_431d76_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="uav",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("registration_number",),
                name="uniq_uav_registration_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="uav",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("serial_number",),
                name="uniq_uav_serial_alive",
            ),
        ),
    ]
