# Generated by Django 5.2.17 on 2026-08-17 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('MAINTENANCE_APPROACHING', 'Maintenance Approaching'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('CRITICAL_COMPONENT', 'Critical Component'), ('LOW_STOCK', 'Low Stock'), ('WORK_ORDER_ASSIGNED', 'Work Order Assigned'), ('WORK_ORDER_COMPLETED', 'Work Order Completed')], max_length=64)),
                ('title_key', models.CharField(max_length=128)),
                ('body_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_d569bc_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_366c29_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('user', 'type', 'source_id'), name='uniq_unread_notification_source')],
            },
        ),
    ]
