from django.db import models


class IntervalUnit(models.TextChoices):
    FLIGHT_HOURS = "FLIGHT_HOURS"
    FLIGHT_CYCLES = "FLIGHT_CYCLES"
    COMPONENT_CYCLES = "COMPONENT_CYCLES"
    CALENDAR_DAYS = "CALENDAR_DAYS"
    CALENDAR_MONTHS = "CALENDAR_MONTHS"
    CALENDAR_YEARS = "CALENDAR_YEARS"


class DueStatus(models.TextChoices):
    NORMAL = "NORMAL"
    APPROACHING = "APPROACHING"
    DUE = "DUE"
    OVERDUE = "OVERDUE"
    CRITICAL = "CRITICAL"


class Priority(models.TextChoices):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InspectionType(models.TextChoices):
    VISUAL = "VISUAL"
    FUNCTIONAL = "FUNCTIONAL"
    MEASUREMENT = "MEASUREMENT"
    OVERHAUL = "OVERHAUL"
    REPLACEMENT = "REPLACEMENT"
    LUBRICATION = "LUBRICATION"
    SOFTWARE = "SOFTWARE"


class RCMStrategy(models.TextChoices):
    SCHEDULED_INSPECTION = "SCHEDULED_INSPECTION"
    SCHEDULED_RESTORATION = "SCHEDULED_RESTORATION"
    SCHEDULED_DISCARD = "SCHEDULED_DISCARD"
    CONDITION_INSPECTION = "CONDITION_INSPECTION"
    FUNCTIONAL_CHECK = "FUNCTIONAL_CHECK"
    CORRECTIVE = "CORRECTIVE"


class WorkOrderStatus(models.TextChoices):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_PARTS = "WAITING_PARTS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MaintenanceType(models.TextChoices):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    SCHEDULED = "SCHEDULED"
    UNSCHEDULED = "UNSCHEDULED"
    INSPECTION = "INSPECTION"
    FUNCTIONAL_CHECK = "FUNCTIONAL_CHECK"


OPEN_WORK_ORDER_STATUSES = (
    WorkOrderStatus.OPEN,
    WorkOrderStatus.ASSIGNED,
    WorkOrderStatus.IN_PROGRESS,
    WorkOrderStatus.WAITING_PARTS,
)

ALERT_DUE_STATUSES = (
    DueStatus.APPROACHING,
    DueStatus.DUE,
    DueStatus.OVERDUE,
    DueStatus.CRITICAL,
)
