# Generated by Django 5.2.17 on 2026-08-17 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("flight_number", models.CharField(max_length=64)),
                ("flown_on", models.DateField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("weather", models.CharField(blank=True, max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                            ("TRAINING", "Training"),
                        ],
                        default="COMPLETED",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("counters_applied", models.BooleanField(default=False)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="uavs.missiontype",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operated_flights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="uavs.uav",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flight",
                "indexes": [
                    models.Index(
                        fields=["uav", "-start_at"], name="flight_uav_id_1c9739_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("flight_number",),
                        name="uniq_flight_number_alive",
                    )
                ],
            },
        ),
    ]
