# Generated by Django 5.2.17 on 2026-08-17 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
        ("fmea", "0001_initial"),
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RCMAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_rcms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rcm_analyses",
                        to="components.componenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rcm_analyses",
                        to="uavs.missiontype",
                    ),
                ),
                (
                    "platform_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rcm_analyses",
                        to="uavs.platformtype",
                    ),
                ),
                (
                    "uav_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rcm_analyses",
                        to="uavs.uavclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rcm_analysis",
            },
        ),
        migrations.CreateModel(
            name="RCMItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("function", models.CharField(max_length=255)),
                ("functional_failure", models.CharField(max_length=255)),
                ("failure_mode", models.TextField()),
                ("failure_effect", models.TextField(blank=True)),
                ("safety_effect", models.BooleanField(default=False)),
                ("operational_effect", models.BooleanField(default=False)),
                (
                    "detectability",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("preventive_feasible", models.BooleanField(default=True)),
                (
                    "suggested_strategy",
                    models.CharField(
                        choices=[
                            ("SCHEDULED_INSPECTION", "Scheduled Inspection"),
                            ("SCHEDULED_RESTORATION", "Scheduled Restoration"),
                            ("SCHEDULED_DISCARD", "Scheduled Discard"),
                            ("CONDITION_INSPECTION", "Condition Inspection"),
                            ("FUNCTIONAL_CHECK", "Functional Check"),
                            ("CORRECTIVE", "Corrective"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("SCHEDULED_INSPECTION", "Scheduled Inspection"),
                            ("SCHEDULED_RESTORATION", "Scheduled Restoration"),
                            ("SCHEDULED_DISCARD", "Scheduled Discard"),
                            ("CONDITION_INSPECTION", "Condition Inspection"),
                            ("FUNCTIONAL_CHECK", "Functional Check"),
                            ("CORRECTIVE", "Corrective"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_overridden", models.BooleanField(default=False)),
                ("rationale", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rcm.rcmanalysis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fmea_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcm_items",
                        to="fmea.fmeaitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rcm_item",
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="rcmanalysis",
            index=models.Index(
                fields=["uav_class", "platform_type", "component_type", "status"],
                name="rcm_analysi_uav_cla_f80f92_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rcmanalysis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_rcm_code_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="rcmitem",
            index=models.Index(
                fields=["analysis", "sequence"], name="rcm_item_analysi_d50bb1_idx"
            ),
        ),
    ]
