# Generated by Django 5.2.17 on 2026-08-17 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
        ("maintenance", "0005_alter_workorder_assigned_technician"),
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureMode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "failure_mode",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Failure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "discovered_during",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("INSPECTION", "Inspection"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "downtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failures",
                        to="components.uavcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failures",
                        to="uavs.uav",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failures",
                        to="maintenance.workorder",
                    ),
                ),
                (
                    "failure_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failures",
                        to="failures.failuremode",
                    ),
                ),
            ],
            options={
                "db_table": "failure",
            },
        ),
        migrations.AddConstraint(
            model_name="failuremode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_failure_mode_code_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="failure",
            index=models.Index(
                fields=["uav", "-occurred_at"], name="failure_uav_id_0aabe9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="failure",
            index=models.Index(
                fields=["resolved_at"], name="failure_resolve_674d3e_idx"
            ),
        ),
    ]
