# Generated by Django 5.2.17 on 2026-08-17 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("tracks_hours", models.BooleanField(default=True)),
                ("tracks_cycles", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "component_type",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="UAVComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                ("part_number", models.CharField(blank=True, max_length=128)),
                ("manufacturer", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operating_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cycle_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTALLED", "Installed"),
                            ("REMOVED", "Removed"),
                            ("QUARANTINE", "Quarantine"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        default="INSTALLED",
                        max_length=32,
                    ),
                ),
                ("last_maintenance_at", models.DateTimeField(blank=True, null=True)),
                ("next_maintenance_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installed_components",
                        to="components.componenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="components.uavcomponent",
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="uavs.uav",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uav_component",
            },
        ),
        migrations.AddConstraint(
            model_name="componenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_component_type_code_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="uavcomponent",
            index=models.Index(
                fields=["uav", "status"], name="uav_compone_uav_id_2f632b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uavcomponent",
            index=models.Index(
                fields=["component_type"], name="uav_compone_compone_8a5266_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="uavcomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    ("removed_at__isnull", True),
                    models.Q(("serial_number", ""), _negated=True),
                ),
                fields=("serial_number",),
                name="uniq_component_serial_installed",
            ),
        ),
    ]
