# Generated by Django 5.2.17 on 2026-08-17 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetemplate",
            name="mission_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_templates",
                to="uavs.missiontype",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetemplate",
            name="platform_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_templates",
                to="uavs.platformtype",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetemplate",
            name="uav_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_templates",
                to="uavs.uavclass",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("uav_class", "platform_type", "mission_type", "approach"),
                name="uniq_active_template_triple",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_template_code_alive",
            ),
        ),
    ]
