# Generated by Django 5.2.17 on 2026-08-17 13:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
        ("maintenance", "0002_initial"),
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceTemplateItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("task_code", models.CharField(max_length=64)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "interval_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "interval_unit",
                    models.CharField(
                        choices=[
                            ("FLIGHT_HOURS", "Flight Hours"),
                            ("FLIGHT_CYCLES", "Flight Cycles"),
                            ("COMPONENT_CYCLES", "Component Cycles"),
                            ("CALENDAR_DAYS", "Calendar Days"),
                            ("CALENDAR_MONTHS", "Calendar Months"),
                            ("CALENDAR_YEARS", "Calendar Years"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("VISUAL", "Visual"),
                            ("FUNCTIONAL", "Functional"),
                            ("MEASUREMENT", "Measurement"),
                            ("OVERHAUL", "Overhaul"),
                            ("REPLACEMENT", "Replacement"),
                            ("LUBRICATION", "Lubrication"),
                            ("SOFTWARE", "Software"),
                        ],
                        default="VISUAL",
                        max_length=32,
                    ),
                ),
                (
                    "rcm_strategy",
                    models.CharField(
                        choices=[
                            ("SCHEDULED_INSPECTION", "Scheduled Inspection"),
                            ("SCHEDULED_RESTORATION", "Scheduled Restoration"),
                            ("SCHEDULED_DISCARD", "Scheduled Discard"),
                            ("CONDITION_INSPECTION", "Condition Inspection"),
                            ("FUNCTIONAL_CHECK", "Functional Check"),
                            ("CORRECTIVE", "Corrective"),
                        ],
                        default="SCHEDULED_INSPECTION",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_items",
                        to="components.componenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="maintenance.maintenancetemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_template_item",
                "ordering": ("sequence", "task_code"),
            },
        ),
        migrations.CreateModel(
            name="MaintenanceDue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("APPROACHING", "Approaching"),
                            ("DUE", "Due"),
                            ("OVERDUE", "Overdue"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "remaining_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "remaining_unit",
                    models.CharField(
                        choices=[
                            ("FLIGHT_HOURS", "Flight Hours"),
                            ("FLIGHT_CYCLES", "Flight Cycles"),
                            ("COMPONENT_CYCLES", "Component Cycles"),
                            ("CALENDAR_DAYS", "Calendar Days"),
                            ("CALENDAR_MONTHS", "Calendar Months"),
                            ("CALENDAR_YEARS", "Calendar Years"),
                        ],
                        max_length=32,
                    ),
                ),
                ("usage_percent", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_dues",
                        to="components.uavcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_dues",
                        to="uavs.uav",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues",
                        to="maintenance.maintenancetemplateitem",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_due",
            },
        ),
        migrations.AddConstraint(
            model_name="maintenancetemplateitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("template", "component_type", "task_code"),
                name="uniq_template_item_task_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancedue",
            index=models.Index(
                fields=["uav", "status"], name="maintenance_uav_id_ddfc2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancedue",
            index=models.Index(fields=["status"], name="maintenance_status_b5f83d_idx"),
        ),
        migrations.AddConstraint(
            model_name="maintenancedue",
            constraint=models.UniqueConstraint(
                fields=("component", "template_item"), name="uniq_due_component_item"
            ),
        ),
    ]
