# Generated by Django 5.2.17 on 2026-08-17 13:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('maintenance', '0003_maintenancetemplateitem_maintenancedue_and_more'),
        ('uavs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetemplateitem',
            name='interval_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=64)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('SCHEDULED', 'Scheduled'), ('UNSCHEDULED', 'Unscheduled'), ('INSPECTION', 'Inspection'), ('FUNCTIONAL_CHECK', 'Functional Check')], default='PREVENTIVE', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PARTS', 'Waiting Parts'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='components.uavcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenancetemplateitem')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='uavs.uav')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_order',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('SCHEDULED', 'Scheduled'), ('UNSCHEDULED', 'Unscheduled'), ('INSPECTION', 'Inspection'), ('FUNCTIONAL_CHECK', 'Functional Check')], max_length=32)),
                ('performed_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('result', models.CharField(blank=True, max_length=64)),
                ('next_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('approach', models.CharField(choices=[('STANDARD', 'Standard'), ('CLASS_SPECIFIC', 'Class Specific')], max_length=32)),
                ('operating_hours_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cycle_count_snapshot', models.PositiveIntegerField(default=0)),
                ('uav_cycles_snapshot', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='components.uavcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='uavs.uav')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='maintenance.workorder')),
            ],
            options={
                'db_table': 'maintenance_record',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['uav', 'status'], name='work_order_uav_id_5b6752_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='work_order_status_8ba28a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('number',), name='uniq_work_order_number_alive'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['uav', 'performed_at'], name='maintenance_uav_id_9b6b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['component', 'performed_at'], name='maintenance_compone_2142e6_idx'),
        ),
    ]
