# Generated by Django 5.2.17 on 2026-08-17 14:13

import django.db.models.deletion
from django.db import migrations, models


def clear_user_assignments(apps, schema_editor):
    WorkOrder = apps.get_model("maintenance", "WorkOrder")
    WorkOrder.objects.exclude(assigned_technician_id=None).update(assigned_technician_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancetemplateitem_interval_value_and_more'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_user_assignments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='technicians.technician'),
        ),
    ]
