from __future__ import annotations

LOCALES = ("tr", "en", "az")

LABELS = {
    "tr": {
        "app": "İHA Bakım Yönetim Sistemi",
        "demo": "DEMO DATA — resmi bakım standardı değildir.",
        "generated": "Oluşturma",
        "uav_history": "İHA geçmişi",
        "maintenance": "Bakım kayıtları",
        "work_order": "İş emirleri",
        "failure": "Arızalar",
        "fmea": "FMEA",
        "rcm": "RCM",
        "fleet": "Filo",
        "reliability": "Güvenilirlik",
        "cost": "Maliyet",
        "uavs": "İHA listesi",
        "components": "Komponentler",
        "flights": "Uçuşlar",
        "failures": "Arızalar",
        "costs": "Maliyetler",
        "identity": "Kimlik",
        "registration": "Tescil",
        "serial": "Seri no",
        "manufacturer": "Üretici",
        "model": "Model",
        "class": "Sınıf",
        "platform": "Platform",
        "mission": "Görev",
        "status": "Durum",
        "hours": "Uçuş saati",
        "number": "No",
        "date": "Tarih",
        "duration": "Süre",
        "type": "Tür",
        "assignee": "Atanan",
        "severity": "Şiddet",
        "mode": "Mod",
        "code": "Kod",
        "title": "Başlık",
        "rpn": "RPN",
        "strategy": "Strateji",
        "part": "Parça",
        "labor": "İşçilik",
        "other": "Diğer",
        "total": "Toplam",
        "name": "Ad",
        "component": "Komponent",
        "mtbf": "MTBF (saat)",
        "mttr": "MTTR (saat)",
        "availability": "Availability",
        "failures_count": "Arıza sayısı",
        "operating": "Çalışma süresi",
        "scope": "Kapsam",
        "task": "Görev",
        "empty": "Kayıt yok.",
        "result": "Sonuç",
        "approach_comparison": "STANDARD vs CLASS_SPECIFIC",
        "approach": "Yaklaşım",
        "uav_count": "İHA sayısı",
        "templates": "Şablon",
        "template_items": "Görev kalemi",
        "due_attention": "Dikkat (vade)",
        "due_overdue": "Gecikmiş vade",
        "wo_open": "Açık iş emri",
    },
    "en": {
        "app": "UAV Maintenance Management System",
        "demo": "DEMO DATA — not an official maintenance standard.",
        "generated": "Generated",
        "uav_history": "UAV history",
        "maintenance": "Maintenance records",
        "work_order": "Work orders",
        "failure": "Failures",
        "fmea": "FMEA",
        "rcm": "RCM",
        "fleet": "Fleet",
        "reliability": "Reliability",
        "cost": "Cost",
        "uavs": "UAV list",
        "components": "Components",
        "flights": "Flights",
        "failures": "Failures",
        "costs": "Costs",
        "identity": "Identity",
        "registration": "Registration",
        "serial": "Serial no",
        "manufacturer": "Manufacturer",
        "model": "Model",
        "class": "Class",
        "platform": "Platform",
        "mission": "Mission",
        "status": "Status",
        "hours": "Flight hours",
        "number": "No",
        "date": "Date",
        "duration": "Duration",
        "type": "Type",
        "assignee": "Assignee",
        "severity": "Severity",
        "mode": "Mode",
        "code": "Code",
        "title": "Title",
        "rpn": "RPN",
        "strategy": "Strategy",
        "part": "Parts",
        "labor": "Labor",
        "other": "Other",
        "total": "Total",
        "name": "Name",
        "component": "Component",
        "mtbf": "MTBF (hours)",
        "mttr": "MTTR (hours)",
        "availability": "Availability",
        "failures_count": "Failure count",
        "operating": "Operating hours",
        "scope": "Scope",
        "task": "Task",
        "empty": "No records.",
        "result": "Result",
        "approach_comparison": "STANDARD vs CLASS_SPECIFIC",
        "approach": "Approach",
        "uav_count": "UAV count",
        "templates": "Templates",
        "template_items": "Task items",
        "due_attention": "Due attention",
        "due_overdue": "Overdue",
        "wo_open": "Open work orders",
    },
    "az": {
        "app": "İHA Texniki Xidmət İdarəetmə Sistemi",
        "demo": "DEMO DATA — rəsmi texniki xidmət standartı deyil.",
        "generated": "Yaradılma",
        "uav_history": "İHA tarixçəsi",
        "maintenance": "Texniki xidmət qeydləri",
        "work_order": "İş əmrləri",
        "failure": "Nasazlıqlar",
        "fmea": "FMEA",
        "rcm": "RCM",
        "fleet": "Donanma",
        "reliability": "Etibarlılıq",
        "cost": "Xərc",
        "uavs": "İHA siyahısı",
        "components": "Komponentlər",
        "flights": "Uçuşlar",
        "failures": "Nasazlıqlar",
        "costs": "Xərclər",
        "identity": "Kimlik",
        "registration": "Qeydiyyat",
        "serial": "Seriya no",
        "manufacturer": "İstehsalçı",
        "model": "Model",
        "class": "Sinif",
        "platform": "Platforma",
        "mission": "Tapşırıq",
        "status": "Status",
        "hours": "Uçuş saatı",
        "number": "No",
        "date": "Tarix",
        "duration": "Müddət",
        "type": "Növ",
        "assignee": "Təyin edilən",
        "severity": "Şiddət",
        "mode": "Mod",
        "code": "Kod",
        "title": "Başlıq",
        "rpn": "RPN",
        "strategy": "Strategiya",
        "part": "Hissə",
        "labor": "Əmək",
        "other": "Digər",
        "total": "Cəmi",
        "name": "Ad",
        "component": "Komponent",
        "mtbf": "MTBF (saat)",
        "mttr": "MTTR (saat)",
        "availability": "Availability",
        "failures_count": "Nasazlıq sayı",
        "operating": "İş müddəti",
        "scope": "Əhatə",
        "task": "Tapşırıq",
        "empty": "Qeyd yoxdur.",
        "result": "Nəticə",
        "approach_comparison": "STANDARD vs CLASS_SPECIFIC",
        "approach": "Yanaşma",
        "uav_count": "İHA sayı",
        "templates": "Şablon",
        "template_items": "Tapşırıq maddəsi",
        "due_attention": "Diqqət (müddət)",
        "due_overdue": "Gecikmiş müddət",
        "wo_open": "Açıq iş əmri",
    },
}


def labels_for(locale: str) -> dict[str, str]:
    return LABELS.get(locale, LABELS["tr"])
