# Generated by Django 5.2.17 on 2026-08-17 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
        ("failures", "0001_initial"),
        ("uavs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FMEA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_fmeas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fmea_analyses",
                        to="components.componenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fmea_analyses",
                        to="uavs.missiontype",
                    ),
                ),
                (
                    "platform_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fmea_analyses",
                        to="uavs.platformtype",
                    ),
                ),
                (
                    "uav_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fmea_analyses",
                        to="uavs.uavclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fmea",
            },
        ),
        migrations.CreateModel(
            name="FMEAItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("function", models.CharField(max_length=255)),
                ("functional_failure", models.CharField(max_length=255)),
                ("failure_mode", models.TextField()),
                ("failure_cause", models.TextField(blank=True)),
                ("failure_effect", models.TextField(blank=True)),
                ("severity", models.PositiveSmallIntegerField()),
                ("occurrence", models.PositiveSmallIntegerField()),
                ("detection", models.PositiveSmallIntegerField()),
                ("rpn", models.PositiveIntegerField(default=0)),
                ("existing_control", models.TextField(blank=True)),
                ("recommended_action", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "catalog_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmea_items",
                        to="failures.failuremode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fmea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fmea.fmea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fmea_item",
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="fmea",
            index=models.Index(
                fields=["uav_class", "platform_type", "component_type", "status"],
                name="fmea_uav_cla_722fa0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fmea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="uniq_fmea_code_alive",
            ),
        ),
        migrations.AddIndex(
            model_name="fmeaitem",
            index=models.Index(
                fields=["fmea", "sequence"], name="fmea_item_fmea_id_405f47_idx"
            ),
        ),
    ]
